### ISSUE TITLE
Bug report Pimenko

### ISSUE THREAD

**Issue by rafajosefernand** [DigiDago/moodle-format_softcourse#108]
### Subject of the issue/enhancement/features
The navigation activities section is gone

### Steps to reproduce
When you access any activity in a course, you can see that the jumpmenu at the bottom of the page does not appear.

### Expected behaviour
The navigation activities (jumpmenu) allow students to access other activities in a faster and convenient way. It is located at the bottom of every activity in a course.

### Actual behaviour
The jumpmenu is not triggered. Softcourse format is killing it. 

### Screenshots (if you can)
![Screen Shot 2022-04-19 at 9 11 46 AM](https://user-images.githubusercontent.com/89751669/164011925-9885f9cb-460b-4f2a-8863-148329f3851b.jpg)

**Comment by CrymSonir** [comment]
Hello,

Unless I am mistaken, this is a recent change on the Moodle side, in terms of the course format we do not manage this navigation.

I cannot therefore respond positively to your request.
