### ISSUE TITLE
Bug report Pimenko

### ISSUE THREAD

**Issue by kwibus** [DigiDago/moodle-format_softcourse#117]
# How to set brandcolor?
I notice that elements like `softcourse-section-img` have:
``` css
    background-color: orange;
    background-color: brandcolor;
```
My browser (chrome) complains that brandcolor is not a valid color, so it defaults to orange. 
Wat is the way to change that orange color?

## What I tried

* I thought it may pick it up from your theme?
I use Boost theme and have set brandcolor option there. But that does not change the option, even after clearing cache.

* Modified css code directly. 
That of course works. but is this the intended way to do this?

**Comment by CrymSonir** [comment]
Indeed, the brandcolor is not taken into account outside of the our theme that we use for our deployments.

We had tried to integrate the value 'just in case' into the CSS, but it seems to not work for boost ...

In the case of Boost, it appears that the brandcolor value is defined much later in the code and, as a result, is not recognized by the course format's CSS.

As you have understood, the only way for you to achieve the desired result would be to define the value you want in the custom CSS.

We are exploring the possibility of adding a feature that would allow you to set the desired color directly in the course settings, but for now, I don't have any dates to provide on this matter :)

Sorry for the delay in response...
