### ISSUE TITLE
Please remove French language files

### ISSUE THREAD

**Issue by germanvaleroelizondo** [DigiDago/moodle-format_softcourse#55]
Hi,

The French language files have been sent to AMOS and they were accepted.
You can now remove the French language strings from this plugin code in GitHub.

You can check all translations for this plugin in the 'Translations' tab of https://moodle.org/plugins/translations.php?plugin=format_softcourse.

Please use AMOS (https://lang.moodle.org/ )for adding the remaining French language string translations.

Same goes for all the other Moodle plugins that you maintain.

**Comment by brunohcury** [comment]
Hello,
can you help me?
I installed this course format and found it really beautiful, but I'm not able to make the necessary restrictions for some sessions, for example:
I need to leave a session named 'certificated' completely hidden and only be released when the student reaches the required average, but they are not succeeding. I tried all the ways but I can't.

Thank you for your help

**Comment by CrymSonir** [comment]
Hello,

Sorry for the time it took us to process your request, the language file will be deleted with the PR #60 

I'm going to look to do the same for the other plugins we maintain.

Thanking you for your return.
