### ISSUE TITLE
 Problem with availability condition

### ISSUE THREAD

**Issue by brunohcury** [DigiDago/moodle-format_softcourse#56]
Hello,
can you help me?
I installed this course format and found it really beautiful, but I'm not able to make the necessary restrictions for some sessions, for example:
I need to leave a session named 'certificated' completely hidden and only be released when the student reaches the required average, but they are not succeeding. I tried all the ways but I can't.

Thank you for your help

**Comment by CrymSonir** [comment]
Hello,

Sorry for the time it has taken us to process your request.

This behavior is not managed by the plugin but by parameters at the level of the section.

I therefore advise you to look at this track:

The setting that I think might help you get the behavior you want is "Restrict access".

This parameter allows you to request a mark higher or lower than a given value either for the entire course or for a specific activity.

I don't think you will be able to hide the section but participants will not have access to it except in the case where they meet the defined criteria.

Best regards.
