### ISSUE TITLE
[Moodle 39] Add/edit image of sections KO

### ISSUE THREAD

**Issue by clementpr** [DigiDago/moodle-format_softcourse#58]
### Subject of the issue/enhancement/features
We can not upload with Moodle 3.9 image to present section

### Steps to reproduce
Go to a course
Turn editing mode on
Try to change image of a section
KO

### Expected behaviour
Upload image on section is OK

### Screenshots
![image](https://user-images.githubusercontent.com/8448884/84515137-5b1aa480-accc-11ea-97a7-25eb7afa1de8.png)

**Comment by CrymSonir** [comment]
Closed with PR https://github.com/DigiDago/moodle-format_softcourse/pull/59
