### ISSUE TITLE
Bug report Pimenko

### ISSUE THREAD

**Issue by azidax** [DigiDago/moodle-format_softcourse#62]
### Subject of the issue/enhancement/features
Hello,

I'm using moodle 3.8.7, theme Lambda and install softcourse plugin on 20 July 2020, I found some difficulties. Can you help me? :

1. I created 1 course in topic format then change to soft course format. suddenly all description course disappear. 

2. i delete the default announcement at general section and add other activity like forum, but when i click start button, i got error 'Activity deletion in progress... ' .  i've wait the progress but it looks like became permanent error.

3.  i have added activity label to section 1 and embed video from youtube as an introduction but sadly the video does not appear when i click start. it jumps to 2nd activity in section 1.

4. What is actually function of section 0?

5.  what is the max words for section title? when i try put a few lines for summary section it appears redundant with the topic section (see my attachment)

I really hope that you can fix the problem so that i can permanently use this awesome plugin. see my attachment as a proof of my difficulities. 

Thank you

![1](https://user-images.githubusercontent.com/60089400/88758382-e37cd800-d19a-11ea-9575-05e013a2efbc.png)
![2](https://user-images.githubusercontent.com/60089400/88758386-e4ae0500-d19a-11ea-81de-4d74f52f6dc9.png)

**Comment by CrymSonir** [comment]
Hello,
Sorry for the delay in response, I think this issue has been resolved on the more recent versions of the course format, do not hesitate to contact us if you still see the problem.
