### ISSUE TITLE
Bug report Pimenko

### ISSUE THREAD

**Issue by numerique-mood** [DigiDago/moodle-format_softcourse#83]
### Subject of the issue/enhancement/features
Suite à l'installation du plugin sur ma plateforme Moodle (3.10.3, thème Moove) de test, quand je crée un cours vierge et que je lui applique le format de cours Soft Course et que j'enregistre, j'ai une erreur qui apparait : Exception : Call to a member function out() on null

### Steps to reproduce
En mode édition de cours, l'erreur n'apparait pas, mes sections sont visibles, je peux ajouter du contenu mais une fois que je sors du mode édition, le message d'erreur apparait mais pas les sections.

### Expected behaviour
J'aimerais bien voir les sections :)

### Actual behaviour
Je ne les vois pas ! re :)

Merci pour votre travail !

### Screenshots (if you can)
![Capture d’écran 2021-05-26 à 16 59 05](https://user-images.githubusercontent.com/84393096/119683959-6666d180-be44-11eb-9592-02b319d2ad64.png)

**Comment by CrymSonir** [comment]
Bonjour,

Pourriez-vous afficher les détails de l'erreur concerner en activant les messages d'erreur pour développeur ( /admin/settings.php?section=debugging ), je ne parviens pas à reproduire le bug même avec un cours 'vierge'.

Nous avons publié une nouvelle version du plugin cette aprem, avez-vous tester cette version du plugin ? :)

Cordialement,

**Comment by numerique-mood** [comment]
Bonjour et merci de votre retour rapide. J'ai installé le plugin il y a un peu plus d'une heure depuis le site de Moodle.
Pour préciser, j'ai recommencé avec un nouveau cours vierge. Première anomalie, lorsque je choisis le format de cours Soft Cours, le choix du nombre de section apparait 2 fois (cf capture)
![Capture d’écran 2021-05-26 à 17 34 16](https://user-images.githubusercontent.com/84393096/119689758-66b59b80-be49-11eb-8444-3a840d96e252.png)

Ensuite j'enregistre et le mode édition est activé, tout est OK, j'ai 4 sections vides. Je quitte le mode édition et deuxième anomalie, les sections vides n'apparaissent pas, seulement la section 0, alors que je n'ai pas demandé de cacher les sections (cf. capture précédente). Et donc j'obtiens l'écran suivant :
![Capture d’écran 2021-05-26 à 17 35 27](https://user-images.githubusercontent.com/84393096/119690178-beec9d80-be49-11eb-8e05-6af0a10502b0.png)

Enfin, suite à votre demande, j'ai activé les messages de débogage pour développeur et voici ce que j'obtiens
![Capture d’écran 2021-05-26 à 17 37 28](https://user-images.githubusercontent.com/84393096/119690324-ddeb2f80-be49-11eb-9b87-c51221d3d5cc.png)

Bien cordialement,
Sébastien

**Comment by CrymSonir** [comment]
Effectivement il y a soucis avec le paramètre "Nombre de sections", mais celui-ci semble ne pas poser de problème particulier en l'état dans la mesure ou je n'ai pas le message d'erreur par la suite ( j'utilise une version moodle 3.10.4+ (Build: 20210514) et Softcourse 3.11rc1 (build: 2021051201).

Vous rencontrez ce message d'erreur uniquement avec le format de cours "softcourse" ?

Pouvez-vous vérifier la version de softcourse utilisez pour votre plateforme  ( "/admin/plugins.php" ) ?

Sylvain.

**Comment by numerique-mood** [comment]
Oui, je confirme que c'est bien la même version du plugin. La seule différence c'est la version de Moodle. Je reste avec la version 3.10.3 (Build: 20210325) car c'est la même que celle que j'utilise pour le groupe scolaire pour lequel je travaille.
Aucun problème à signaler avec d'autres formats de cours (cf. liste ci-dessous)
![Capture d’écran 2021-05-26 à 18 43 00](https://user-images.githubusercontent.com/84393096/119699778-cb292880-be52-11eb-9c4d-fe53785afc85.png)
Je vais essayer de réinstaller ce plugin pour voir si cela change quelque chose...
Sébastien

**Comment by numerique-mood** [comment]
Pour info, une réinstallation n'a rien changé.

**Comment by numerique-mood** [comment]
L'erreur n'apparait qu'à partir du moment où j'ajoute une ressource dans une des sections vides. Ici, je n'ai ajouté qu'une "simple" étiquette contenant le mot "Hello" dans la section 1.

**Comment by CrymSonir** [comment]
Okay le soucis vient de là !
Il semble avoir un conflit avec l'activité label dans le cas ou celle-ci est la première activité de la section !
Nous allons publié un correctif au plus vite :)

**Comment by numerique-mood** [comment]
Je découvre votre réponse au moment au je finis d'éditer le mien... Ce qui semble confirmer le problème.

**Comment by CrymSonir** [comment]
Je vous notifierai dés que le correctif est déployé, normalement d'ici la fin de semaine :)

**Comment by numerique-mood** [comment]
Ça marche, merci !

**Comment by numerique-mood** [comment]
Re-bonsoir,
Juste pour information, j'ai supprimé les étiquettes et j'ai utilisé les descriptions des sections, tout est OK. 

En revanche que ce soit avec Moove ou avec Boost, on ne distingue pas comme sur les anciennes versions (j'ai un autre bac à sable Moodle 3.10.3 et Soft Course 2.0 (2020062014) le tout fonctionnant comme prévu) l'image par défaut des sections (chapeau sur fond jaune)  ainsi que les boutons pour modifier, supprimer l'image ou commencer le cours qui apparaissent au survol. Ils semblent être blanc sur fond blanc et je ne peux me fier qu'aux info-bulles. Je n'ai aucune modification de CSS sur mon Moodle Test
![Capture d’écran 2021-05-26 à 22 02 02](https://user-images.githubusercontent.com/84393096/119723808-2ddbed80-be6e-11eb-957b-59bd4c1ac714.png)

Bien cordialement,
Sébastien

**Comment by CrymSonir** [comment]
Bonjour Sébastien,

Nous avons publié la version contenant le correctif à l'instant, cela devrait avoir réglé les soucis que vous nous aviez remonté :)

Bien à vous,
Sylvain.

**Comment by numerique-mood** [comment]
Bonjour,
Merci pour le message ! Je viens de mettre à jour votre plugin à l'instant et je constate les éléments suivants :

- mes dernières remarques sur les boutons "invisibles" est corrigée et la couleur orange de base est de retour (d'ailleurs comment peut-on la changer facilement ? Je n'ai pas trouvé de réglages et qu'entendez-vous par "brandcolor" dans le changelog de version ?)
- l'erreur n'apparait plus lorsqu'une étiquette est ajoutée en premier mais (désolé...) si on laisse cette étiquette seule dans la section (ce qui n'a pas beaucoup de sens je le reconnais...) la section n'apparait pas lorsqu'on quitte le mode édition. Il faut alors ajouter une autre activité ou ressource pour que cette section apparaisse.

Merci en tout cas de votre disponibilité, de votre réactivité et de ce que vous faites pour la communauté Moodle !
Bien à vous,
Sébastien

**Comment by CrymSonir** [comment]
L'option brandcolor est une option qui normalement se retrouve au niveau des settings du thème que vous utilisez ( elle est normalement présente dans la plus part des thèmes ).

Mais je suis en train de voir que pour les thèmes autre que celui que nous utilisons cela semble ne pas fonctionner, je vais essayer de voir si je trouve une solution alternative pour que ça fonctionne pour tous les thèmes :)

Concernant les labels vu qu'ils ne disposent pas d'un type de page propre ( comme le forum, page ... ), du coup on n'affiche pas la section si il ne contient que des activités cachés, restreints ou non affiché ( je sais pas si je suis claire ).

Bien à vous,

**Comment by numerique-mood** [comment]
Bonjour,
Merci pour l'explication à propos des labels, c'est très clair !
J'ai effectivement trouvé l'option brandcolor sur le thème Moove mais elle n'affecte pas la couleur de fond des images du plugin Soft Course qui restent orange. Peut-être pour une future amélioration ? 
Encore merci pour votre réactivité,
Bien à vous,
Sébastien

**Comment by CrymSonir** [comment]
Bonjour,
Nous allons regarder pour essayer de trouver une solution concernant la brandcolor mais effectivement nous verrons ça plus tard ( cela va demander plus de temps ... ).
Je ferme donc cette issue, n'hésitez pas à revenir vers nous si vous constatez d'autre problèmes :)
Bien à vous,
Sylvain.
