### ISSUE TITLE
cant press start 

### ISSUE THREAD

**Issue by RazlanModernLMS** [DigiDago/moodle-format_softcourse#92]
@clementpr I need help. Why I cant press start at the image.

**Comment by RazlanModernLMS** [comment]
![c1](https://user-images.githubusercontent.com/72715777/127260555-c5dff3f1-d7be-4472-8e47-821c8cf2d00b.png)

**Comment by CrymSonir** [comment]
Hello,
For me there is no problem at this level.
Wich version of the plugin are you using?
Wich version of moodle are you using?
Can you also tell me which browser you are using?

**Comment by RazlanModernLMS** [comment]
Hi, thank you for the fast response.

**Comment by CrymSonir** [comment]
Can you try adding this css code to your custom css:
`.stretched-link::after {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1;
    pointer-events: auto;
    content: "";
    background-color: rgba(0,0,0,0);
}`

Can you tell me if this fixes the problem ? :)
